### ISSUE TITLE
jobs stay in QUEUED state

### ISSUE THREAD

**Issue by ingenieroariel** [SEL-Columbia/modelrunner#107]
I deployed a production instance of modelrunner on two different Amazon instances.

After uploading a job it stayed in QUEUED state and redis does not show workers connecting to the queue.

How do I unlock jobs? Could it be related to workers not being able to connect to redis queue?

**Comment by chrisnatali** [comment]
Your hunch about workers not being able to connect to redis queues sounds like a good one.  

The general flow of a successful job through modelrunner is:
1.  Primary receives job with data files via upload [[here](https://github.com/SEL-Columbia/modelrunner/blob/master/modelrunner/primary_server.py#L80)]
2.  Primary puts job metadata on queue for one of the workers waiting on that queue to take [[here](https://github.com/SEL-Columbia/modelrunner/blob/master/modelrunner/primary_server.py#L112)]
3.  Worker retrieves data files from primary and starts running job [[here](https://github.com/SEL-Columbia/modelrunner/blob/master/modelrunner/worker_server.py#L108)]
4.  Worker finishes job and notifies primary [[here](https://github.com/SEL-Columbia/modelrunner/blob/master/modelrunner/worker_server.py#L161)]
5.  Primary picks up job result files from worker url (all job data files end up on the primary if they complete successfully) [[here](https://github.com/SEL-Columbia/modelrunner/blob/master/modelrunner/primary_server.py#L156)]

All the workers need access to Redis in order to take jobs off the queue.  If workers can't connect to Redis, you should see a failure in the worker log created in worker startup [script](https://github.com/SEL-Columbia/modelrunner/blob/master/scripts/start_worker_production.sh#L18). 

The instance running on modelrunner.io just has password based authentication setup to connect to redis.  That can be configured in the "redis_url" param with something like "redis://:MYPWD@host:port" (all done in the worker config file...template here).  Once the workers have been able to connect, you can verify their availability by going to your master server's "primary_host/status" page (i.e. modelrunner.io/status).  I created that page to make it easier to determine if workers were actively connected.  

It's important that you bring up the workers AFTER the redis server has been brought up (otherwise they'll fail to connect upon initializing and not retry).  

Note that files are retrieved via http servers running on all nodes that participate in a modelrunner deployment.  Only the notifications that job has been uploaded, completed and other status/kill messages are communicated via Redis queues.  

If you're still having trouble, you can paste the log from your primary, worker and redis modelrunner server startup scripts here and I can try to help interpret what's happening.

**Comment by ingenieroariel** [comment]
This fixed it. Thanks!
